#! /bin/sh

xrandr --output HDMI-0 --mode 1920x1080 --rate 119.98
nitrogen --restore 
picom --animations -b
polybar example  &

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 

bspc config border_width         1
bspc config window_gap          12
bspc config border_radius 	9

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^2' follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a discord desktop='^4'
